namespace Glacier.Vector.Compute;

internal static class GpuVectorKernels
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	vector_dot_scan_fp32

.visible .entry vector_dot_scan_fp32(
	.param .u64 vector_dot_scan_fp32_param_0,
	.param .u64 vector_dot_scan_fp32_param_1,
	.param .u64 vector_dot_scan_fp32_param_2,
	.param .u32 vector_dot_scan_fp32_param_3,
	.param .u32 vector_dot_scan_fp32_param_4
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<50>;
	.reg .b64 	%rd<57>;


	ld.param.u64 	%rd28, [vector_dot_scan_fp32_param_0];
	ld.param.u64 	%rd29, [vector_dot_scan_fp32_param_1];
	ld.param.u64 	%rd27, [vector_dot_scan_fp32_param_2];
	ld.param.u32 	%r25, [vector_dot_scan_fp32_param_3];
	ld.param.u32 	%r24, [vector_dot_scan_fp32_param_4];
	cvta.to.global.u64 	%rd1, %rd29;
	cvta.to.global.u64 	%rd2, %rd28;
	mov.u32 	%r26, %ctaid.x;
	mov.u32 	%r27, %ntid.x;
	mov.u32 	%r28, %tid.x;
	mad.lo.s32 	%r1, %r27, %r26, %r28;
	setp.ge.s32 	%p1, %r1, %r25;
	@%p1 bra 	$L__BB0_16;

	mul.lo.s32 	%r30, %r1, %r24;
	cvt.s64.s32 	%rd3, %r30;
	setp.lt.s32 	%p2, %r24, 4;
	mov.u32 	%r45, 0;
	mov.f32 	%f134, 0f00000000;
	mov.f32 	%f135, %f134;
	mov.f32 	%f136, %f134;
	mov.f32 	%f137, %f134;
	@%p2 bra 	$L__BB0_8;

	add.s32 	%r33, %r24, -4;
	shr.u32 	%r2, %r33, 2;
	add.s32 	%r34, %r2, 1;
	and.b32  	%r44, %r34, 3;
	setp.lt.u32 	%p3, %r33, 12;
	mov.f32 	%f137, 0f00000000;
	mov.u32 	%r45, 0;
	mov.f32 	%f136, %f137;
	mov.f32 	%f135, %f137;
	mov.f32 	%f134, %f137;
	@%p3 bra 	$L__BB0_5;

	sub.s32 	%r39, %r2, %r44;
	shl.b64 	%rd30, %rd3, 2;
	add.s64 	%rd31, %rd1, %rd30;
	add.s64 	%rd49, %rd31, 32;
	mov.f32 	%f137, 0f00000000;
	mov.u32 	%r45, 0;
	mov.u64 	%rd50, %rd2;

$L__BB0_4:
	ld.global.nc.f32 	%f50, [%rd49+-32];
	ld.global.nc.f32 	%f51, [%rd50];
	fma.rn.f32 	%f52, %f51, %f50, %f134;
	ld.global.nc.f32 	%f53, [%rd49+-28];
	ld.global.nc.f32 	%f54, [%rd50+4];
	fma.rn.f32 	%f55, %f54, %f53, %f135;
	ld.global.nc.f32 	%f56, [%rd49+-24];
	ld.global.nc.f32 	%f57, [%rd50+8];
	fma.rn.f32 	%f58, %f57, %f56, %f136;
	ld.global.nc.f32 	%f59, [%rd49+-20];
	ld.global.nc.f32 	%f60, [%rd50+12];
	fma.rn.f32 	%f61, %f60, %f59, %f137;
	ld.global.nc.f32 	%f62, [%rd49+-16];
	ld.global.nc.f32 	%f63, [%rd50+16];
	fma.rn.f32 	%f64, %f63, %f62, %f52;
	ld.global.nc.f32 	%f65, [%rd49+-12];
	ld.global.nc.f32 	%f66, [%rd50+20];
	fma.rn.f32 	%f67, %f66, %f65, %f55;
	ld.global.nc.f32 	%f68, [%rd49+-8];
	ld.global.nc.f32 	%f69, [%rd50+24];
	fma.rn.f32 	%f70, %f69, %f68, %f58;
	ld.global.nc.f32 	%f71, [%rd49+-4];
	ld.global.nc.f32 	%f72, [%rd50+28];
	fma.rn.f32 	%f73, %f72, %f71, %f61;
	ld.global.nc.f32 	%f74, [%rd49];
	ld.global.nc.f32 	%f75, [%rd50+32];
	fma.rn.f32 	%f76, %f75, %f74, %f64;
	ld.global.nc.f32 	%f77, [%rd49+4];
	ld.global.nc.f32 	%f78, [%rd50+36];
	fma.rn.f32 	%f79, %f78, %f77, %f67;
	ld.global.nc.f32 	%f80, [%rd49+8];
	ld.global.nc.f32 	%f81, [%rd50+40];
	fma.rn.f32 	%f82, %f81, %f80, %f70;
	ld.global.nc.f32 	%f83, [%rd49+12];
	ld.global.nc.f32 	%f84, [%rd50+44];
	fma.rn.f32 	%f85, %f84, %f83, %f73;
	ld.global.nc.f32 	%f86, [%rd49+16];
	ld.global.nc.f32 	%f87, [%rd50+48];
	fma.rn.f32 	%f134, %f87, %f86, %f76;
	ld.global.nc.f32 	%f88, [%rd49+20];
	ld.global.nc.f32 	%f89, [%rd50+52];
	fma.rn.f32 	%f135, %f89, %f88, %f79;
	ld.global.nc.f32 	%f90, [%rd49+24];
	ld.global.nc.f32 	%f91, [%rd50+56];
	fma.rn.f32 	%f136, %f91, %f90, %f82;
	ld.global.nc.f32 	%f92, [%rd49+28];
	ld.global.nc.f32 	%f93, [%rd50+60];
	fma.rn.f32 	%f137, %f93, %f92, %f85;
	add.s32 	%r45, %r45, 16;
	add.s64 	%rd50, %rd50, 64;
	add.s64 	%rd49, %rd49, 64;
	add.s32 	%r39, %r39, -4;
	setp.ne.s32 	%p4, %r39, -1;
	@%p4 bra 	$L__BB0_4;

$L__BB0_5:
	setp.eq.s32 	%p5, %r44, 0;
	@%p5 bra 	$L__BB0_8;

	cvt.s64.s32 	%rd32, %r45;
	add.s64 	%rd33, %rd32, %rd3;
	shl.b64 	%rd34, %rd33, 2;
	add.s64 	%rd52, %rd1, %rd34;
	mul.wide.s32 	%rd35, %r45, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd51, %rd36, 8;

$L__BB0_7:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f94, [%rd52];
	ld.global.nc.f32 	%f95, [%rd51+-8];
	fma.rn.f32 	%f134, %f95, %f94, %f134;
	ld.global.nc.f32 	%f96, [%rd52+4];
	ld.global.nc.f32 	%f97, [%rd51+-4];
	fma.rn.f32 	%f135, %f97, %f96, %f135;
	ld.global.nc.f32 	%f98, [%rd52+8];
	ld.global.nc.f32 	%f99, [%rd51];
	fma.rn.f32 	%f136, %f99, %f98, %f136;
	ld.global.nc.f32 	%f100, [%rd52+12];
	ld.global.nc.f32 	%f101, [%rd51+4];
	fma.rn.f32 	%f137, %f101, %f100, %f137;
	add.s32 	%r45, %r45, 4;
	add.s64 	%rd52, %rd52, 16;
	add.s64 	%rd51, %rd51, 16;
	add.s32 	%r44, %r44, -1;
	setp.ne.s32 	%p6, %r44, 0;
	@%p6 bra 	$L__BB0_7;

$L__BB0_8:
	add.f32 	%f102, %f136, %f137;
	add.f32 	%f103, %f134, %f135;
	add.f32 	%f142, %f103, %f102;
	setp.ge.s32 	%p7, %r45, %r24;
	@%p7 bra 	$L__BB0_15;

	sub.s32 	%r36, %r24, %r45;
	and.b32  	%r47, %r36, 3;
	setp.eq.s32 	%p8, %r47, 0;
	mov.u32 	%r48, %r45;
	@%p8 bra 	$L__BB0_12;

	cvt.s64.s32 	%rd37, %r45;
	add.s64 	%rd38, %rd37, %rd3;
	shl.b64 	%rd39, %rd38, 2;
	add.s64 	%rd54, %rd1, %rd39;
	mul.wide.s32 	%rd40, %r45, 4;
	add.s64 	%rd53, %rd2, %rd40;
	mov.u32 	%r48, %r45;

$L__BB0_11:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f105, [%rd54];
	ld.global.nc.f32 	%f106, [%rd53];
	fma.rn.f32 	%f142, %f106, %f105, %f142;
	add.s32 	%r48, %r48, 1;
	add.s64 	%rd54, %rd54, 4;
	add.s64 	%rd53, %rd53, 4;
	add.s32 	%r47, %r47, -1;
	setp.ne.s32 	%p9, %r47, 0;
	@%p9 bra 	$L__BB0_11;

$L__BB0_12:
	not.b32 	%r37, %r45;
	add.s32 	%r38, %r37, %r24;
	setp.lt.u32 	%p10, %r38, 3;
	@%p10 bra 	$L__BB0_15;

	cvt.s64.s32 	%rd41, %r48;
	add.s64 	%rd42, %rd41, %rd3;
	shl.b64 	%rd43, %rd42, 2;
	add.s64 	%rd56, %rd1, %rd43;
	mul.wide.s32 	%rd44, %r48, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd55, %rd45, 8;

$L__BB0_14:
	ld.global.nc.f32 	%f107, [%rd56];
	ld.global.nc.f32 	%f108, [%rd55+-8];
	fma.rn.f32 	%f109, %f108, %f107, %f142;
	ld.global.nc.f32 	%f110, [%rd56+4];
	ld.global.nc.f32 	%f111, [%rd55+-4];
	fma.rn.f32 	%f112, %f111, %f110, %f109;
	ld.global.nc.f32 	%f113, [%rd56+8];
	ld.global.nc.f32 	%f114, [%rd55];
	fma.rn.f32 	%f115, %f114, %f113, %f112;
	ld.global.nc.f32 	%f116, [%rd56+12];
	ld.global.nc.f32 	%f117, [%rd55+4];
	fma.rn.f32 	%f142, %f117, %f116, %f115;
	add.s64 	%rd56, %rd56, 16;
	add.s64 	%rd55, %rd55, 16;
	add.s32 	%r48, %r48, 4;
	setp.lt.s32 	%p11, %r48, %r24;
	@%p11 bra 	$L__BB0_14;

$L__BB0_15:
	cvta.to.global.u64 	%rd46, %rd27;
	mul.wide.s32 	%rd47, %r1, 4;
	add.s64 	%rd48, %rd46, %rd47;
	st.global.f32 	[%rd48], %f142;

$L__BB0_16:
	ret;

}
	// .globl	vector_batch_dot_scan_fp32
.visible .entry vector_batch_dot_scan_fp32(
	.param .u64 vector_batch_dot_scan_fp32_param_0,
	.param .u64 vector_batch_dot_scan_fp32_param_1,
	.param .u64 vector_batch_dot_scan_fp32_param_2,
	.param .u32 vector_batch_dot_scan_fp32_param_3,
	.param .u32 vector_batch_dot_scan_fp32_param_4,
	.param .u32 vector_batch_dot_scan_fp32_param_5
)
{
	.reg .pred 	%p<14>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<62>;


	ld.param.u64 	%rd32, [vector_batch_dot_scan_fp32_param_0];
	ld.param.u64 	%rd33, [vector_batch_dot_scan_fp32_param_1];
	ld.param.u64 	%rd31, [vector_batch_dot_scan_fp32_param_2];
	ld.param.u32 	%r27, [vector_batch_dot_scan_fp32_param_3];
	ld.param.u32 	%r25, [vector_batch_dot_scan_fp32_param_4];
	ld.param.u32 	%r26, [vector_batch_dot_scan_fp32_param_5];
	cvta.to.global.u64 	%rd1, %rd33;
	cvta.to.global.u64 	%rd2, %rd32;
	mov.u32 	%r28, %ctaid.x;
	mov.u32 	%r29, %ntid.x;
	mov.u32 	%r30, %tid.x;
	mad.lo.s32 	%r1, %r29, %r28, %r30;
	setp.ge.s32 	%p1, %r1, %r27;
	mov.u32 	%r2, %ctaid.y;
	setp.ge.s32 	%p2, %r2, %r26;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB1_16;

	mul.lo.s32 	%r32, %r2, %r25;
	cvt.s64.s32 	%rd3, %r32;
	mul.lo.s32 	%r33, %r1, %r25;
	cvt.s64.s32 	%rd4, %r33;
	setp.lt.s32 	%p4, %r25, 4;
	mov.u32 	%r49, 0;
	mov.f32 	%f134, 0f00000000;
	mov.f32 	%f135, %f134;
	mov.f32 	%f136, %f134;
	mov.f32 	%f137, %f134;
	@%p4 bra 	$L__BB1_8;

	add.s32 	%r36, %r25, -4;
	shr.u32 	%r3, %r36, 2;
	add.s32 	%r37, %r3, 1;
	and.b32  	%r48, %r37, 3;
	setp.lt.u32 	%p5, %r36, 12;
	mov.f32 	%f137, 0f00000000;
	mov.u32 	%r49, 0;
	mov.f32 	%f136, %f137;
	mov.f32 	%f135, %f137;
	mov.f32 	%f134, %f137;
	@%p5 bra 	$L__BB1_5;

	sub.s32 	%r43, %r3, %r48;
	shl.b64 	%rd34, %rd3, 2;
	add.s64 	%rd35, %rd2, %rd34;
	add.s64 	%rd55, %rd35, 32;
	shl.b64 	%rd36, %rd4, 2;
	add.s64 	%rd37, %rd1, %rd36;
	add.s64 	%rd54, %rd37, 32;
	mov.f32 	%f137, 0f00000000;
	mov.u32 	%r49, 0;

$L__BB1_4:
	ld.global.nc.f32 	%f50, [%rd54+-32];
	ld.global.nc.f32 	%f51, [%rd55+-32];
	fma.rn.f32 	%f52, %f51, %f50, %f134;
	ld.global.nc.f32 	%f53, [%rd54+-28];
	ld.global.nc.f32 	%f54, [%rd55+-28];
	fma.rn.f32 	%f55, %f54, %f53, %f135;
	ld.global.nc.f32 	%f56, [%rd54+-24];
	ld.global.nc.f32 	%f57, [%rd55+-24];
	fma.rn.f32 	%f58, %f57, %f56, %f136;
	ld.global.nc.f32 	%f59, [%rd54+-20];
	ld.global.nc.f32 	%f60, [%rd55+-20];
	fma.rn.f32 	%f61, %f60, %f59, %f137;
	ld.global.nc.f32 	%f62, [%rd54+-16];
	ld.global.nc.f32 	%f63, [%rd55+-16];
	fma.rn.f32 	%f64, %f63, %f62, %f52;
	ld.global.nc.f32 	%f65, [%rd54+-12];
	ld.global.nc.f32 	%f66, [%rd55+-12];
	fma.rn.f32 	%f67, %f66, %f65, %f55;
	ld.global.nc.f32 	%f68, [%rd54+-8];
	ld.global.nc.f32 	%f69, [%rd55+-8];
	fma.rn.f32 	%f70, %f69, %f68, %f58;
	ld.global.nc.f32 	%f71, [%rd54+-4];
	ld.global.nc.f32 	%f72, [%rd55+-4];
	fma.rn.f32 	%f73, %f72, %f71, %f61;
	ld.global.nc.f32 	%f74, [%rd54];
	ld.global.nc.f32 	%f75, [%rd55];
	fma.rn.f32 	%f76, %f75, %f74, %f64;
	ld.global.nc.f32 	%f77, [%rd54+4];
	ld.global.nc.f32 	%f78, [%rd55+4];
	fma.rn.f32 	%f79, %f78, %f77, %f67;
	ld.global.nc.f32 	%f80, [%rd54+8];
	ld.global.nc.f32 	%f81, [%rd55+8];
	fma.rn.f32 	%f82, %f81, %f80, %f70;
	ld.global.nc.f32 	%f83, [%rd54+12];
	ld.global.nc.f32 	%f84, [%rd55+12];
	fma.rn.f32 	%f85, %f84, %f83, %f73;
	ld.global.nc.f32 	%f86, [%rd54+16];
	ld.global.nc.f32 	%f87, [%rd55+16];
	fma.rn.f32 	%f134, %f87, %f86, %f76;
	ld.global.nc.f32 	%f88, [%rd54+20];
	ld.global.nc.f32 	%f89, [%rd55+20];
	fma.rn.f32 	%f135, %f89, %f88, %f79;
	ld.global.nc.f32 	%f90, [%rd54+24];
	ld.global.nc.f32 	%f91, [%rd55+24];
	fma.rn.f32 	%f136, %f91, %f90, %f82;
	ld.global.nc.f32 	%f92, [%rd54+28];
	ld.global.nc.f32 	%f93, [%rd55+28];
	fma.rn.f32 	%f137, %f93, %f92, %f85;
	add.s32 	%r49, %r49, 16;
	add.s64 	%rd55, %rd55, 64;
	add.s64 	%rd54, %rd54, 64;
	add.s32 	%r43, %r43, -4;
	setp.ne.s32 	%p6, %r43, -1;
	@%p6 bra 	$L__BB1_4;

$L__BB1_5:
	setp.eq.s32 	%p7, %r48, 0;
	@%p7 bra 	$L__BB1_8;

	shl.b64 	%rd38, %rd4, 2;
	add.s64 	%rd57, %rd1, %rd38;
	shl.b64 	%rd39, %rd3, 2;
	add.s64 	%rd56, %rd2, %rd39;
	mul.wide.s32 	%rd13, %r49, 4;

$L__BB1_7:
	.pragma ""nounroll"";
	add.s64 	%rd40, %rd56, %rd13;
	add.s64 	%rd41, %rd57, %rd13;
	ld.global.nc.f32 	%f94, [%rd41];
	ld.global.nc.f32 	%f95, [%rd40];
	fma.rn.f32 	%f134, %f95, %f94, %f134;
	ld.global.nc.f32 	%f96, [%rd41+4];
	ld.global.nc.f32 	%f97, [%rd40+4];
	fma.rn.f32 	%f135, %f97, %f96, %f135;
	ld.global.nc.f32 	%f98, [%rd41+8];
	ld.global.nc.f32 	%f99, [%rd40+8];
	fma.rn.f32 	%f136, %f99, %f98, %f136;
	ld.global.nc.f32 	%f100, [%rd41+12];
	ld.global.nc.f32 	%f101, [%rd40+12];
	fma.rn.f32 	%f137, %f101, %f100, %f137;
	add.s32 	%r49, %r49, 4;
	add.s64 	%rd57, %rd57, 16;
	add.s64 	%rd56, %rd56, 16;
	add.s32 	%r48, %r48, -1;
	setp.ne.s32 	%p8, %r48, 0;
	@%p8 bra 	$L__BB1_7;

$L__BB1_8:
	add.f32 	%f102, %f136, %f137;
	add.f32 	%f103, %f134, %f135;
	add.f32 	%f142, %f103, %f102;
	setp.ge.s32 	%p9, %r49, %r25;
	@%p9 bra 	$L__BB1_15;

	sub.s32 	%r39, %r25, %r49;
	and.b32  	%r51, %r39, 3;
	setp.eq.s32 	%p10, %r51, 0;
	mov.u32 	%r52, %r49;
	@%p10 bra 	$L__BB1_12;

	cvt.s64.s32 	%rd42, %r49;
	add.s64 	%rd43, %rd42, %rd4;
	shl.b64 	%rd44, %rd43, 2;
	add.s64 	%rd59, %rd1, %rd44;
	add.s64 	%rd45, %rd42, %rd3;
	shl.b64 	%rd46, %rd45, 2;
	add.s64 	%rd58, %rd2, %rd46;
	mov.u32 	%r52, %r49;

$L__BB1_11:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f105, [%rd59];
	ld.global.nc.f32 	%f106, [%rd58];
	fma.rn.f32 	%f142, %f106, %f105, %f142;
	add.s32 	%r52, %r52, 1;
	add.s64 	%rd59, %rd59, 4;
	add.s64 	%rd58, %rd58, 4;
	add.s32 	%r51, %r51, -1;
	setp.ne.s32 	%p11, %r51, 0;
	@%p11 bra 	$L__BB1_11;

$L__BB1_12:
	not.b32 	%r40, %r49;
	add.s32 	%r41, %r40, %r25;
	setp.lt.u32 	%p12, %r41, 3;
	@%p12 bra 	$L__BB1_15;

	shl.b64 	%rd47, %rd4, 2;
	add.s64 	%rd61, %rd1, %rd47;
	shl.b64 	%rd48, %rd3, 2;
	add.s64 	%rd60, %rd2, %rd48;
	mul.wide.s32 	%rd26, %r52, 4;

$L__BB1_14:
	add.s64 	%rd49, %rd60, %rd26;
	add.s64 	%rd50, %rd61, %rd26;
	ld.global.nc.f32 	%f107, [%rd50];
	ld.global.nc.f32 	%f108, [%rd49];
	fma.rn.f32 	%f109, %f108, %f107, %f142;
	ld.global.nc.f32 	%f110, [%rd50+4];
	ld.global.nc.f32 	%f111, [%rd49+4];
	fma.rn.f32 	%f112, %f111, %f110, %f109;
	ld.global.nc.f32 	%f113, [%rd50+8];
	ld.global.nc.f32 	%f114, [%rd49+8];
	fma.rn.f32 	%f115, %f114, %f113, %f112;
	ld.global.nc.f32 	%f116, [%rd50+12];
	ld.global.nc.f32 	%f117, [%rd49+12];
	fma.rn.f32 	%f142, %f117, %f116, %f115;
	add.s64 	%rd61, %rd61, 16;
	add.s64 	%rd60, %rd60, 16;
	add.s32 	%r52, %r52, 4;
	setp.lt.s32 	%p13, %r52, %r25;
	@%p13 bra 	$L__BB1_14;

$L__BB1_15:
	mad.lo.s32 	%r42, %r1, %r26, %r2;
	cvta.to.global.u64 	%rd51, %rd31;
	mul.wide.s32 	%rd52, %r42, 4;
	add.s64 	%rd53, %rd51, %rd52;
	st.global.f32 	[%rd53], %f142;

$L__BB1_16:
	ret;

}
	// .globl	vector_l2_scan_fp32
.visible .entry vector_l2_scan_fp32(
	.param .u64 vector_l2_scan_fp32_param_0,
	.param .u64 vector_l2_scan_fp32_param_1,
	.param .u64 vector_l2_scan_fp32_param_2,
	.param .u32 vector_l2_scan_fp32_param_3,
	.param .u32 vector_l2_scan_fp32_param_4
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<168>;
	.reg .b32 	%r<50>;
	.reg .b64 	%rd<57>;


	ld.param.u64 	%rd28, [vector_l2_scan_fp32_param_0];
	ld.param.u64 	%rd29, [vector_l2_scan_fp32_param_1];
	ld.param.u64 	%rd27, [vector_l2_scan_fp32_param_2];
	ld.param.u32 	%r25, [vector_l2_scan_fp32_param_3];
	ld.param.u32 	%r24, [vector_l2_scan_fp32_param_4];
	cvta.to.global.u64 	%rd1, %rd29;
	cvta.to.global.u64 	%rd2, %rd28;
	mov.u32 	%r26, %ctaid.x;
	mov.u32 	%r27, %ntid.x;
	mov.u32 	%r28, %tid.x;
	mad.lo.s32 	%r1, %r27, %r26, %r28;
	setp.ge.s32 	%p1, %r1, %r25;
	@%p1 bra 	$L__BB2_16;

	mul.lo.s32 	%r30, %r1, %r24;
	cvt.s64.s32 	%rd3, %r30;
	setp.lt.s32 	%p2, %r24, 4;
	mov.u32 	%r45, 0;
	mov.f32 	%f159, 0f00000000;
	mov.f32 	%f160, %f159;
	mov.f32 	%f161, %f159;
	mov.f32 	%f162, %f159;
	@%p2 bra 	$L__BB2_8;

	add.s32 	%r33, %r24, -4;
	shr.u32 	%r2, %r33, 2;
	add.s32 	%r34, %r2, 1;
	and.b32  	%r44, %r34, 3;
	setp.lt.u32 	%p3, %r33, 12;
	mov.f32 	%f162, 0f00000000;
	mov.u32 	%r45, 0;
	mov.f32 	%f161, %f162;
	mov.f32 	%f160, %f162;
	mov.f32 	%f159, %f162;
	@%p3 bra 	$L__BB2_5;

	sub.s32 	%r39, %r2, %r44;
	shl.b64 	%rd30, %rd3, 2;
	add.s64 	%rd31, %rd1, %rd30;
	add.s64 	%rd49, %rd31, 32;
	mov.f32 	%f162, 0f00000000;
	mov.u32 	%r45, 0;
	mov.u64 	%rd50, %rd2;

$L__BB2_4:
	ld.global.nc.f32 	%f50, [%rd49+-32];
	ld.global.nc.f32 	%f51, [%rd50];
	sub.f32 	%f52, %f51, %f50;
	ld.global.nc.f32 	%f53, [%rd49+-28];
	ld.global.nc.f32 	%f54, [%rd50+4];
	sub.f32 	%f55, %f54, %f53;
	ld.global.nc.f32 	%f56, [%rd49+-24];
	ld.global.nc.f32 	%f57, [%rd50+8];
	sub.f32 	%f58, %f57, %f56;
	ld.global.nc.f32 	%f59, [%rd49+-20];
	ld.global.nc.f32 	%f60, [%rd50+12];
	sub.f32 	%f61, %f60, %f59;
	fma.rn.f32 	%f62, %f52, %f52, %f159;
	fma.rn.f32 	%f63, %f55, %f55, %f160;
	fma.rn.f32 	%f64, %f58, %f58, %f161;
	fma.rn.f32 	%f65, %f61, %f61, %f162;
	ld.global.nc.f32 	%f66, [%rd49+-16];
	ld.global.nc.f32 	%f67, [%rd50+16];
	sub.f32 	%f68, %f67, %f66;
	ld.global.nc.f32 	%f69, [%rd49+-12];
	ld.global.nc.f32 	%f70, [%rd50+20];
	sub.f32 	%f71, %f70, %f69;
	ld.global.nc.f32 	%f72, [%rd49+-8];
	ld.global.nc.f32 	%f73, [%rd50+24];
	sub.f32 	%f74, %f73, %f72;
	ld.global.nc.f32 	%f75, [%rd49+-4];
	ld.global.nc.f32 	%f76, [%rd50+28];
	sub.f32 	%f77, %f76, %f75;
	fma.rn.f32 	%f78, %f68, %f68, %f62;
	fma.rn.f32 	%f79, %f71, %f71, %f63;
	fma.rn.f32 	%f80, %f74, %f74, %f64;
	fma.rn.f32 	%f81, %f77, %f77, %f65;
	ld.global.nc.f32 	%f82, [%rd49];
	ld.global.nc.f32 	%f83, [%rd50+32];
	sub.f32 	%f84, %f83, %f82;
	ld.global.nc.f32 	%f85, [%rd49+4];
	ld.global.nc.f32 	%f86, [%rd50+36];
	sub.f32 	%f87, %f86, %f85;
	ld.global.nc.f32 	%f88, [%rd49+8];
	ld.global.nc.f32 	%f89, [%rd50+40];
	sub.f32 	%f90, %f89, %f88;
	ld.global.nc.f32 	%f91, [%rd49+12];
	ld.global.nc.f32 	%f92, [%rd50+44];
	sub.f32 	%f93, %f92, %f91;
	fma.rn.f32 	%f94, %f84, %f84, %f78;
	fma.rn.f32 	%f95, %f87, %f87, %f79;
	fma.rn.f32 	%f96, %f90, %f90, %f80;
	fma.rn.f32 	%f97, %f93, %f93, %f81;
	ld.global.nc.f32 	%f98, [%rd49+16];
	ld.global.nc.f32 	%f99, [%rd50+48];
	sub.f32 	%f100, %f99, %f98;
	ld.global.nc.f32 	%f101, [%rd49+20];
	ld.global.nc.f32 	%f102, [%rd50+52];
	sub.f32 	%f103, %f102, %f101;
	ld.global.nc.f32 	%f104, [%rd49+24];
	ld.global.nc.f32 	%f105, [%rd50+56];
	sub.f32 	%f106, %f105, %f104;
	ld.global.nc.f32 	%f107, [%rd49+28];
	ld.global.nc.f32 	%f108, [%rd50+60];
	sub.f32 	%f109, %f108, %f107;
	fma.rn.f32 	%f159, %f100, %f100, %f94;
	fma.rn.f32 	%f160, %f103, %f103, %f95;
	fma.rn.f32 	%f161, %f106, %f106, %f96;
	fma.rn.f32 	%f162, %f109, %f109, %f97;
	add.s32 	%r45, %r45, 16;
	add.s64 	%rd50, %rd50, 64;
	add.s64 	%rd49, %rd49, 64;
	add.s32 	%r39, %r39, -4;
	setp.ne.s32 	%p4, %r39, -1;
	@%p4 bra 	$L__BB2_4;

$L__BB2_5:
	setp.eq.s32 	%p5, %r44, 0;
	@%p5 bra 	$L__BB2_8;

	cvt.s64.s32 	%rd32, %r45;
	add.s64 	%rd33, %rd32, %rd3;
	shl.b64 	%rd34, %rd33, 2;
	add.s64 	%rd52, %rd1, %rd34;
	mul.wide.s32 	%rd35, %r45, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd51, %rd36, 8;

$L__BB2_7:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f110, [%rd52];
	ld.global.nc.f32 	%f111, [%rd51+-8];
	sub.f32 	%f112, %f111, %f110;
	ld.global.nc.f32 	%f113, [%rd52+4];
	ld.global.nc.f32 	%f114, [%rd51+-4];
	sub.f32 	%f115, %f114, %f113;
	ld.global.nc.f32 	%f116, [%rd52+8];
	ld.global.nc.f32 	%f117, [%rd51];
	sub.f32 	%f118, %f117, %f116;
	ld.global.nc.f32 	%f119, [%rd52+12];
	ld.global.nc.f32 	%f120, [%rd51+4];
	sub.f32 	%f121, %f120, %f119;
	fma.rn.f32 	%f159, %f112, %f112, %f159;
	fma.rn.f32 	%f160, %f115, %f115, %f160;
	fma.rn.f32 	%f161, %f118, %f118, %f161;
	fma.rn.f32 	%f162, %f121, %f121, %f162;
	add.s32 	%r45, %r45, 4;
	add.s64 	%rd52, %rd52, 16;
	add.s64 	%rd51, %rd51, 16;
	add.s32 	%r44, %r44, -1;
	setp.ne.s32 	%p6, %r44, 0;
	@%p6 bra 	$L__BB2_7;

$L__BB2_8:
	add.f32 	%f122, %f161, %f162;
	add.f32 	%f123, %f159, %f160;
	add.f32 	%f167, %f123, %f122;
	setp.ge.s32 	%p7, %r45, %r24;
	@%p7 bra 	$L__BB2_15;

	sub.s32 	%r36, %r24, %r45;
	and.b32  	%r47, %r36, 3;
	setp.eq.s32 	%p8, %r47, 0;
	mov.u32 	%r48, %r45;
	@%p8 bra 	$L__BB2_12;

	cvt.s64.s32 	%rd37, %r45;
	add.s64 	%rd38, %rd37, %rd3;
	shl.b64 	%rd39, %rd38, 2;
	add.s64 	%rd54, %rd1, %rd39;
	mul.wide.s32 	%rd40, %r45, 4;
	add.s64 	%rd53, %rd2, %rd40;
	mov.u32 	%r48, %r45;

$L__BB2_11:
	.pragma ""nounroll"";
	ld.global.nc.f32 	%f125, [%rd54];
	ld.global.nc.f32 	%f126, [%rd53];
	sub.f32 	%f127, %f126, %f125;
	fma.rn.f32 	%f167, %f127, %f127, %f167;
	add.s32 	%r48, %r48, 1;
	add.s64 	%rd54, %rd54, 4;
	add.s64 	%rd53, %rd53, 4;
	add.s32 	%r47, %r47, -1;
	setp.ne.s32 	%p9, %r47, 0;
	@%p9 bra 	$L__BB2_11;

$L__BB2_12:
	not.b32 	%r37, %r45;
	add.s32 	%r38, %r37, %r24;
	setp.lt.u32 	%p10, %r38, 3;
	@%p10 bra 	$L__BB2_15;

	cvt.s64.s32 	%rd41, %r48;
	add.s64 	%rd42, %rd41, %rd3;
	shl.b64 	%rd43, %rd42, 2;
	add.s64 	%rd56, %rd1, %rd43;
	mul.wide.s32 	%rd44, %r48, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd55, %rd45, 8;

$L__BB2_14:
	ld.global.nc.f32 	%f128, [%rd56];
	ld.global.nc.f32 	%f129, [%rd55+-8];
	sub.f32 	%f130, %f129, %f128;
	fma.rn.f32 	%f131, %f130, %f130, %f167;
	ld.global.nc.f32 	%f132, [%rd56+4];
	ld.global.nc.f32 	%f133, [%rd55+-4];
	sub.f32 	%f134, %f133, %f132;
	fma.rn.f32 	%f135, %f134, %f134, %f131;
	ld.global.nc.f32 	%f136, [%rd56+8];
	ld.global.nc.f32 	%f137, [%rd55];
	sub.f32 	%f138, %f137, %f136;
	fma.rn.f32 	%f139, %f138, %f138, %f135;
	ld.global.nc.f32 	%f140, [%rd56+12];
	ld.global.nc.f32 	%f141, [%rd55+4];
	sub.f32 	%f142, %f141, %f140;
	fma.rn.f32 	%f167, %f142, %f142, %f139;
	add.s64 	%rd56, %rd56, 16;
	add.s64 	%rd55, %rd55, 16;
	add.s32 	%r48, %r48, 4;
	setp.lt.s32 	%p11, %r48, %r24;
	@%p11 bra 	$L__BB2_14;

$L__BB2_15:
	cvta.to.global.u64 	%rd46, %rd27;
	mul.wide.s32 	%rd47, %r1, 4;
	add.s64 	%rd48, %rd46, %rd47;
	st.global.f32 	[%rd48], %f167;

$L__BB2_16:
	ret;

}

";
}
